# Watchdogger sample configuration

actions:
  log_it: 
    type: log_action
  mail_message:
    type: send_mail
    to: hahn@netseven.it
    sender: averell@newgods.org
    
watchers:
  test_hn:
    type: http_watcher
    url: http://www.foobar.or/
    actions: 
      - log_it
      - mail_message
    
interval: 3
# logfile: daemon.log
pidfile: watcher.pid
log_level: warn